### ISSUE TITLE
🛠 Tooling: Add linting to prevent blank/redundant JSDoc/TSDoc tags

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/ts-api-utils#152]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

From https://github.com/JoshuaKGoldberg/ts-api-utils/pull/70#discussion_r1111115566:

> > ```ts
> > @param token
> > @returns
> > ```
>
> [Question] There's no benefit I can see to `@param <name>` or `@returns` with no additional information. That can all be inferred from TypeScript without risk of mismatching (note the name being wrong here). Is there any reason to leave them in?
> 
> [Request] Let's take them out if there's no change from them?

Is there some kind of standard ESLint plugin or set of plugins for this?

### Additional Info

https://github.com/gajus/eslint-plugin-jsdoc and https://www.npmjs.com/package/eslint-plugin-tsdoc look snazzy. I haven't looked too deeply.

I wonder if this should also be backported to https://github.com/JoshuaKGoldberg/template-typescript-node-package...

**Comment by RebeccaStevens** [comment]
It would be better to use [eslint-plugin-jsdoc](https://www.npmjs.com/package/eslint-plugin-jsdoc) than [eslint-plugin-tsdoc](https://www.npmjs.com/package/eslint-plugin-tsdoc).
