### ISSUE TITLE
Versioning plan for a 1.0

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/ts-api-utils#170]
# Overview

Another appreciated friendly prompt from @bradzacher - we're getting to the point where this will be used in typescript-eslint@v6. I think it makes sense to hit 1.0 by the time we get there.

@bradzacher @RebeccaStevens what do you think about the following plan:

1. Once each of the following is resolved, increase the minor number by one
    * #124
    * #163
    * ...any other significant issues/PRs
2. Once typescript-eslint@v6 is looking pretty close to ready, bump the version to 1.0.0-beta
3. Bump the version to 1.0.0 in time for typescript-eslint@v6

**Comment by RebeccaStevens** [comment]
Sounds good to me.

**Comment by JoshuaKGoldberg** [comment]
typescript-eslint@v6 is looking pretty close to ready, so I'll bump to 1.0.0-beta now. 🚀

**Comment by JoshuaKGoldberg** [comment]
I release 1.0.0. ✅
