### ISSUE TITLE
🚀 Feature: Add type guard for the error type

### ISSUE THREAD

**Issue by RebeccaStevens** [JoshuaKGoldberg/ts-api-utils#226]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Essentially a function that returns `isIntrinsicType(type) && type.intrinsicName === "error"`.

### Additional Info

I'm not sure what the best name for the function would be. Possible names:

- `isErrorType`
  - \+ short and simple
  - \- users may confuse with the JS `Error` object's type
- `isTypeError`
  - \+ short and simple
  - \- inconsistent with other type type guards (other ones always end with "Type")
- `isIntrinsicErrorType`
  - \+ consistent with other intrinsic type guards
  - \- users may think "Intrinsic Error" is a subtype of error

**Comment by JoshuaKGoldberg** [comment]
Hmm good question. I do like consistency - `isIntrinsicErrorType` makes the most sense to me... and the downside seems much smaller than the other two options'. Voting for `isIntrinsicErrorType`!
