### ISSUE TITLE
🚀 Feature: Port collectVariableUsage from tsutils

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/ts-api-utils#263]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

`tsutils` has a `collectVariableUsage` API: https://github.com/microsoft/TypeScript/issues/28026 -> https://github.com/ajafff/tsutils/blob/03b4df15d14702f9c7a128ac3fae77171778d613/util/usage.ts#L162-L164. We haven't ported that over yet.

I use it in TypeStat, which means not having it is blocking https://github.com/JoshuaKGoldberg/TypeStat/pull/1123.

### Additional Info

cc @bradzacher @RebeccaStevens - do you see any reason not to port the old `collectVariableUsage` API here? 

Note that https://github.com/ajafff/tsutils/issues/38 tracks refactoring the API to be more type aware. I don't have the energy to make that port. But I suppose we could always take it in as a followup.

**Comment by bradzacher** [comment]
We already have this in tseslint via @typescript-eslint/scope-manager so it's not a tool we'd use there.

**Comment by RebeccaStevens** [comment]
No rejections from me.
