### ISSUE TITLE
🐛 Bug: Cannot be used directly from node due to module setup

### ISSUE THREAD

**Issue by phryneas** [JoshuaKGoldberg/ts-api-utils#277]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

Importing this module from a `.mjs` file should work

### Actual

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/tronic/tmp/apollo-client/node_modules/ts-api-tools/lib/tokens' imported from /Users/tronic/tmp/apollo-client/node_modules/ts-api-tools/lib/comments.js
```

### Additional Info

The import statements in the `lib` folder would require a `.js` extension for this to work.

Here's a pretty minimal reproduction:

https://github.com/apollographql/apollo-client/tree/65e31716c7f363158309e990946f73e410c73837/config/eslint-rules

(Run `npm run test` in the `config/eslint-rules` folder)

Also visible here: If you rename these files to `.js` to use CommonJS require, TypeScript complains:
![image](https://github.com/JoshuaKGoldberg/ts-api-utils/assets/4282439/603ffb30-f78b-4118-a46c-aab3c64d2ce1)

Those complaints only go away after removing the `type: "module"` from this module's `package.json` - it seems that TypeScript ignores the `require` `exports` conditions once `type: "module"` is present.

**Comment by JoshuaKGoldberg** [comment]
> `ts-api-tools`

The package is `ts-api-` **`utils`** now 😄. I'd originally called it _`tools`_ then realized _`utils`_ makes more sense as a name (#27).

**Comment by JoshuaKGoldberg** [comment]
> `ts-api-tools`

The package is `ts-api-` **`utils`** now 😄. I'd originally called it _`tools`_ then realized _`utils`_ makes more sense as a name (#27). 

I tried swapping them out locally and it all worked. 

It is unfortunate how realistic-looking the old npm package is. I ran `npm deprecate ts-api-tools "Renamed to ts-api-utils"` just now to help with that.

Cheers, and thanks for using! ❤️‍🔥

**Comment by phryneas** [comment]
Dang! That one is still mentioned in the Eslint docs, here: https://typescript-eslint.io/developers/custom-rules/#typed-rules

![image](https://github.com/JoshuaKGoldberg/ts-api-utils/assets/4282439/caf444d6-f530-4d32-8844-34d403bd527e)


A miractle you get so few downloads on the wrong ones in that light ^^


Thanks for looking into it!

**Comment by JoshuaKGoldberg** [comment]
> A miractle you get so few downloads on the wrong ones in that light ^^

That's one way of looking at it. Another would be that almost nobody reads the docs 🫠🫠🫠
