### ISSUE TITLE
🛠 Tooling: Release job blocked from pushing to GitHub 

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/ts-api-utils#30]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

This GitHub Action `release.yml` Release job failed to push to GitHub: https://github.com/JoshuaKGoldberg/ts-api-utils/actions/runs/4115398512/jobs/7104053426

```plaintext
 M package.json
ERROR remote: Permission to JoshuaKGoldberg/ts-api-utils.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/JoshuaKGoldberg/ts-api-utils/': The requested URL returned error: 403
```

A later run that fails to publish a package version to npm twice (since the Git commit that bumped version never was pushed to GitHub): https://github.com/JoshuaKGoldberg/ts-api-utils/actions/runs/4115932211/jobs/7105309725

```plaintext
npm notice Publishing to https://registry.npmjs.org/
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/ts-api-tools - You cannot publish over the previously published versions: 0.0.18.
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
```

...but I set up a dev PAT token. Why is this broken?

**Comment by RebeccaStevens** [comment]
Have you set the "Workflow permissions"? https://github.com/JoshuaKGoldberg/ts-api-utils/settings/actions

**Comment by RebeccaStevens** [comment]
> I set up a dev PAT token. Why is this broken?

You've specified to different secrets: `ACCESS_TOKEN` and `GITHUB_TOKEN`. `GITHUB_TOKEN` is the one being used by `release-it` so that one has the issue. I assume this token simply doesn't exist.

In #71 I changed the token that `release-it` uses to the default github token and gave it permission to push content changes.
Your PAT token is still needed for adding and removing branch protection as the default token can't be given such permission.

**Comment by JoshuaKGoldberg** [comment]
Ah! @johnnyreilly is this what you were referring to in https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/159?

We should add these fixes to template-typescript-node-package too. Awesome.
