### ISSUE TITLE
🚀 Feature: Remove `isTextualLiteral`

### ISSUE THREAD

**Issue by RebeccaStevens** [JoshuaKGoldberg/ts-api-utils#32]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

`isTextualLiteral` is just TypeScript's `isStringLiteralLike` by another name.

**Comment by JoshuaKGoldberg** [comment]
Heh, I'm guessing you're referring to [this type guard from `tsutils`](https://github.com/ajafff/tsutils/blob/e263f863652a408317cfe555c335d80a1637a8fc/typeguard/2.8/node.ts#L630-L633)?

```ts
export function isTextualLiteral(node: ts.Node): node is ts.StringLiteral | ts.NoSubstitutionTemplateLiteral {
    return node.kind === ts.SyntaxKind.StringLiteral ||
        node.kind === ts.SyntaxKind.NoSubstitutionTemplateLiteral;
}
```

If so: yes, agreed, that does match the naming scheme better and makes sense.

**Comment by RebeccaStevens** [comment]
TypeScript actually defines `isStringLiteralLike` which is identical to `isTextualLiteral`. `isTextualLiteral` should just be removed.
