### ISSUE TITLE
🛠 Tooling: Knip config is giving false positives for exported exports

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/ts-api-utils#45]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

See https://github.com/JoshuaKGoldberg/ts-api-utils/pull/33 & https://github.com/JoshuaKGoldberg/ts-api-utils/pull/40. We had to add `"ignore": ["src/nodes/typeGuards/!(*.test).ts"` to `knip.jsonc` because it was flagging functions that are used.

### Additional Info

Filed upstream as https://github.com/webpro/knip/issues/62.

**Comment by RebeccaStevens** [comment]
Is this worth closing as we have a workaround?

**Comment by JoshuaKGoldberg** [comment]
Yeah 🚀
