### ISSUE TITLE
🚀 Feature: be able to determine where a type is defined

### ISSUE THREAD

**Issue by RebeccaStevens** [JoshuaKGoldberg/ts-api-utils#501]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Essentially adds the `typeMatchesSpecifier` function from [ts-declaration-location](https://www.npmjs.com/package/ts-declaration-location).

This function is only for testing where a type is defined, not filtering the type based on its name or anything else. That could be new functionality in the future.

**Comment by JoshuaKGoldberg** [comment]
It's an interesting idea! My personal inclination is that this should be a separate package. `ts-api-utils` is a lot of very generalized utilities. `typesMatchesSpecifier` is a pretty specific format that's also still relatively new in usage. Having the separate [ts-declaration-location](https://www.npmjs.com/package/ts-declaration-location) be able to iterate on its own feels right to me. Just my two cents 😄 putting into discussion.

**Comment by RebeccaStevens** [comment]
Yeah that makes sense. I'm perfectly happy to continue with it in its own repo.
