### ISSUE TITLE
🐛 Bug: package is listed as `type: module` even though it only exports `.cjs` files

### ISSUE THREAD

**Issue by bradzacher** [JoshuaKGoldberg/ts-api-utils#54]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

```jsonc
// tsconfig.json
{
  "compilerOptions": {
    // ...
    "moduleResolution": "node16",
    // ...
  }
}
```

```jsonc
// package.json
{
  // ...
  "type": "commonjs"
  // ...
}
```

```ts
// file.ts
import * as foo from 'ts-api-utils';
```

Expected: this should work

### Actual

```
The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("ts-api-tools")' call instead.
  To convert this file to an ECMAScript module, change its file extension to '.mts' or create a local package.json file with `{ "type": "module" }`. ts(1479)
```

### Additional Info

The root package.json is marked as `type: module`
https://github.com/JoshuaKGoldberg/ts-api-utils/blob/ba48dde317a7d88db22a1cba34bc820f92c5c9e3/package.json#L11

But the build only outputs one `.cjs` file (https://unpkg.com/browse/ts-api-utils@0.0.21/lib/)

It also lists an `import` path, but such a path is not included in the released package:
https://github.com/JoshuaKGoldberg/ts-api-utils/blob/ba48dde317a7d88db22a1cba34bc820f92c5c9e3/package.json#L15

I think the former is correct - but i guess that TS doesn't accept it? Is it a problem with this module or the consuming TS config?

**Comment by JoshuaKGoldberg** [comment]
Ah, this is a bug yeah. #37 should fix it. Thanks for reporting!

**Comment by bradzacher** [comment]
https://twitter.com/bradzacher/status/1628248371143274498
Okay doing some investigation, I've figured out how this package is supposed to be setup if it's got dual exports.

What `type: "module"` does is tells consumers "all ambiguous files covered by the `package.json` should be treated as `.mjs` files". TS mirrors this same behaviour locally developing `.ts` files, and externally with the `.d.ts` files.

Currently the package is configured with `package.exports['./'].types = "./lib/index.d.ts"`
By declaring `type: "module"`, you're telling TS that `./lib/index.d.ts` is ESM - i.e. it is supposed to be `./lib/index.d.mts` -> meaning it is not allowed to be `require`d from a CJS file.

This is why we're getting the TS error in @typescript-eslint. We're a CJS package, so TS is blocking us from `require`ing an ESM file - which is technically correct.
Sadly in this instance TS blocks hard here because (I believe) there are no types for the CJS export. It just sees ESM types, so it essentially ignores the CJS file (@andrewbranch is this the correct way to phrase it?)

So how can this be fixed?

(1) add a separate `.d.cts` def file for the commonjs export.
Ideally it should use `export =`, but ultimately just exporting a new file with exactly the same content, just with the correct extension should be "okay".

(2) fix the package.json config

(2.a) One option is to remove the `exports.types` field altogether and just add the relevant `.d.ts`/`.d.cts` files - TS is smart enough to find the correct files (it's what andrew recommends). But *personally* I like to be explicit, so I'd personally go with (b)...

(2.b) update the package.json config to:
```json
	"type": "module",
	"exports": {
		".": {
			"types": {
				"import": "./lib/index.d.ts",
				"require": "./lib/index.d.cts"
			},
			"import": "./lib/index.js",
			"require": "./lib/index.cjs"
		}
	},
```
(TIL you can nest the condition within the `types` condition!)
This will explicitly tell TS where to find the types for each of exported files.

(3) [optional] name the files to be explicitly `.mts`.
You don't need to do this, but it's a nice thing to do to remove ambiguity in the resolution everywhere. Completely optional aesthetic step.

**Comment by RebeccaStevens** [comment]
Ahh, I was having this same issue a little while back in my other libraries; I fixed it by implementing option 2b there.

I wasn't noticing this issue in this project so I assume somewhere between TS 4.7 and the current 4.9, they fixed this so that `.d.ts` files could be treated as either `cjs` or `mjs` based on the context of what file was responsible from them being loaded. I guess I was wrong and this issue still remains.

**Comment by bradzacher** [comment]
I tested 2.b by manually modifying the module within my @typescript-eslint repo and it worked as expected.

I changed the `export { ... }` to `export = { ... }`, and it meant I couldn't do `import * as tools from 'ts-api-utils'` any more (ofc), but other than that - worked fine, again.
