### ISSUE TITLE
🛠 Tooling: Missing some version tags

### ISSUE THREAD

**Issue by RebeccaStevens** [JoshuaKGoldberg/ts-api-utils#585]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

Some tags are missing.
`v1.4.1` and `v1.3.0` were never created.

### Additional Info

Is this supposed to be automated or do these tags need to be created manually?

**Comment by JoshuaKGoldberg** [comment]
They should have been automated, looks like the job was broken... 👀

**Comment by JoshuaKGoldberg** [comment]
At this point, it looks like the release job's breakage was between publishing to npm and updating releases on GitHub. Which is quite annoying to debug. If someone else wants to sift through the Git history / published versions to determine which commits go where, please let me know 😅. I'm going to close this out for now.
