### ISSUE TITLE
🚀 Feature: Remove dependency on semver

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/ts-api-utils#589]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

From https://github.com/JoshuaKGoldberg/ts-api-utils/pull/576#issuecomment-2498260612 -> #587: we already have an `isTsVersionAtLeast` function internally. But the `typeIsLiteral` function uses the `semver` package dependency instead. 

I agree with @fisker (thanks for noting this! ❤️) that we can consolidate on `isTsVersionAtLeast` and get rid of the `semver` dependency. 

cc @RebeccaStevens because this overlaps with #576?

### Additional Info

Co-authored-by: @fisker

**Comment by RebeccaStevens** [comment]
fix by #587
