### ISSUE TITLE
`isFunctionScopeBoundary`'s name suggests that it should return a boolean

### ISSUE THREAD

**Issue by RebeccaStevens** [JoshuaKGoldberg/ts-api-utils#68]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

https://github.com/JoshuaKGoldberg/ts-api-utils/blob/acd3836863656f217dfb301a3987a9103a77be1c/src/scopes.ts#L11

The `is` prefix on this function's name suggests that it should return a boolean rather than a `ScopeBoundary`.

The only way I can imagine users using this function as is, is to immediately compare the return value to 
a `ScopeBoundary` value. The function should just return a boolean in the first place.

I'm guessing the reasoning for the function current implementation is so that it can be easily expanded upon, return different types of `ScopeBoundary` in future. However, if this is the case, the function would want a new name anyway, such as `getScopeBoundary`.

**Comment by JoshuaKGoldberg** [comment]
Agreed. I like `getFunctionScopeBoundary` as a name. 👍 let's rename!

**Comment by RebeccaStevens** [comment]
> Agreed. I like `getFunctionScopeBoundary` as a name. 👍 let's rename!

Are you sure you want to rename the function as opposed to just changing its return type?
I don't see any point in the function returning a `ScopeBoundary` instead of just a `boolean`.

**Comment by JoshuaKGoldberg** [comment]
Hmm. They're not implemented in this package (yet?), but there are other functions that reuse `ScopeBoundary` does have other values on the `ScopeBoundary` enum in `tsutils`...

```ts
export function isScopeBoundary(node: ts.Node): ScopeBoundary {
    return isFunctionScopeBoundary(node) || isBlockScopeBoundary(node) || isTypeScopeBoundary(node);
}
```

Those functions are nice to have - and I think it would be a nice add to `ts-api-utils` to add them back in. WDYT?

**Comment by RebeccaStevens** [comment]
I'll be good to have those function but I think they should all return `boolean`s. Except for `isScopeBoundary` which I'd suggest we write as:

```ts
export function getScopeBoundary(node: ts.Node): ScopeBoundary {
    return isFunctionScopeBoundary(node)
      ? ScopeBoundary.Function
      : isBlockScopeBoundary(node)
      ? ScopeBoundary.Block
      : isTypeScopeBoundary(node)
      ? ScopeBoundary.Type
      : ScopeBoundary.None
}
```
