### ISSUE TITLE
rename `hasModifier` to `includesModifier` (or `containsModifier`)

### ISSUE THREAD

**Issue by RebeccaStevens** [JoshuaKGoldberg/ts-api-utils#69]
https://github.com/JoshuaKGoldberg/ts-api-utils/blob/acd3836863656f217dfb301a3987a9103a77be1c/src/modifiers.ts#LL6C23-L6C23

The name `hasModifier` suggests that the function would work on a node, like how `ts.hasJSDocParameterTags` and `ts.hasRestParameter` work.

I suggest using the either term `includes` or `contains` instead of `has` to make this a little more clear.

**Comment by JoshuaKGoldberg** [comment]
Hmm that's a good point - I'm inclined to agree. Since the function internally refers to `includes` - maybe that one?

cc @bradzacher, do you have any thoughts?
