### ISSUE TITLE
📝 Documentation: Update README.md h1 title to match package name

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/ts-api-utils#73]
### Bug Report Checklist

- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

As [reported by @jmchor on Twitter](https://twitter.com/jmchor/status/1627213834673848321): the `#` h1 in the README.md right now says _TypeScript API Tools_. That's a holdover from when the package was called `ts-api-tools`.

Let's rename that to _TypeScript API Utils_.

### Additional Info

This should apply to the README.md and any other files that reference the old name.

**Comment by 20A31A0558** [comment]
Can I work on this?

**Comment by JoshuaKGoldberg** [comment]
Ah sorry @20A31A0558, #74 already resolved it. But there are other [`good first issue`s](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22) remaining if you're interested! ❤️

**Comment by hi-malik** [comment]
@JoshuaKGoldberg can you please provide me any `good first issues`

**Comment by JoshuaKGoldberg** [comment]
Yup, see the link in my post just before yours 🙂
