### ISSUE TITLE
rename `isNumericPropertyName` to `isNumericString`

### ISSUE THREAD

**Issue by RebeccaStevens** [JoshuaKGoldberg/ts-api-utils#78]
## Overview

This function's implantation and typings allows for it to be used in a much more generic way that the name suggests. Do we want to use a more generic name?

**Comment by RebeccaStevens** [comment]
Actually, on second/thrrd (forth?) thought, `isNumericString` would suggest that the function allows for things like leading zeros and non-base ten numbers. Maybe `isNumericPropertyName` is the most generic we can get.

@JoshuaKGoldberg thoughts?

**Comment by RebeccaStevens** [comment]
Now on seventh though, `isNumericString` doesn't imply those things anymore than `isNumericPropertyName` does.

**Comment by JoshuaKGoldberg** [comment]
Haha yeah I think it's fine as-is, for the reasons you mention in the second post. Property names are more strict than general strings.
