### ISSUE TITLE
🐛 Bug: `isLiteralType` implementation isn't strict enough for its type guard

### ISSUE THREAD

**Issue by RebeccaStevens** [JoshuaKGoldberg/ts-api-utils#82]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

`isLiteralType` should return false when given a literal type that isn't a "LiteralType" as defined in typescript.

For example: `isLiteralType` should return `false` for a boolean literal as a boolean literal isn't a `LiteralType`.

### Actual

It returns `true`.

### Additional Info

Should `isLiteralType`'s implementation be made more strict by testing the type of the `value` property?
Or should the type guard be made more generic by using an new `UnknownLiteralType` type that both `LiteralType` and other "literal types" extend?

**Comment by JoshuaKGoldberg** [comment]
I like the latter, using `UnknownLiteralType`. TypeScript `Type`s have a method `isLiteral(): this is LiteralType;` already:

```ts
    isLiteral(): this is LiteralType {
        return !!(this.flags & (TypeFlags.StringLiteral | TypeFlags.NumberLiteral | TypeFlags.BigIntLiteral));
    }
```

**Comment by RebeccaStevens** [comment]
> TypeScript `Type`s have a method `isLiteral(): this is LiteralType;` already:
> 
> ```ts
>     isLiteral(): this is LiteralType {
>         return !!(this.flags & (TypeFlags.StringLiteral | TypeFlags.NumberLiteral | TypeFlags.BigIntLiteral));
>     }
> ```

Oh, in that case, should we remove our `isLiteralType` all together? or at least deprecate it in favor of the ts version.

**Comment by JoshuaKGoldberg** [comment]
`UnknownLiteralType` strikes me as useful though. I'd vote to keep it in.

**Comment by RebeccaStevens** [comment]
I meant, do we want to remove `isLiteralType` seems `isLiteral` exists?
We can keep the `isUnknownLiteralType` (in #80) as its own thing.

**Comment by JoshuaKGoldberg** [comment]
Oh got it - yes, that makes sense to me. Agreed!
