### ISSUE TITLE
🐛 Bug: `isFunctionScopeBoundary` should state no for function-like types.

### ISSUE THREAD

**Issue by RebeccaStevens** [JoshuaKGoldberg/ts-api-utils#89]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

The `FunctionType` node below should return `false`/`ScopeBoundary.None`

```ts
type T = () => void;
```

### Actual

It returns `true`/`ScopeBoundary.Function`

### Additional Info

There isn't a scope boundary when dealing with types, only declarations.

**Comment by JoshuaKGoldberg** [comment]
Hmm, what about type level shadowing?

```ts
type T = (param: number) => (param: string) => void
```

**Comment by RebeccaStevens** [comment]
I didn't think about that. Nevermind then, close this.
