### ISSUE TITLE
🛠 Tooling: Unneeded releases going out

### ISSUE THREAD

**Issue by RebeccaStevens** [JoshuaKGoldberg/ts-api-utils#95]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/ts-api-utils/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

`ci:` commits seem to trigger releases - they shouldn't

**Comment by RebeccaStevens** [comment]
Any particular reason why we're using `should-semantic-release` and `release-it` instead of [semantic-release](https://www.npmjs.com/package/semantic-release)?

**Comment by JoshuaKGoldberg** [comment]
https://github.com/semantic-release/semantic-release/issues/2639 😢 I really like semantic-release but they just don't support 0.X versions. Nor are they very actively maintained right now (relative to the amount of user activity).

**Comment by RebeccaStevens** [comment]
Would it be worth switching over once we release 1.0?

**Comment by JoshuaKGoldberg** [comment]
Ehhhhhhh in theory... but http://github.com/JoshuaKGoldberg/template-typescript-node-package is on release-it still and I'd like to keep the tooling in sync. In theory we should be able to wrestle `release-it` & co. into submission. If that just can't happen I suppose we can always switch back post-1.0.
